def ask_user
    print "What is your first card? "
    card1 = get_card
    card1 = card_value(card1)
    print "Great! What is your second card? "
    card2 = get_card
    card2 = card_value(card2)
    print "Ok. Now what is the dealer's upcard? "
    upcard = get_card
    upcard = card_value(upcard)
    return card1, card2, upcard

end

def get_card
    loop do
        card = gets.chomp
        return card if valid_card(card)
        print "Not a card. Try again: "
    end
end

def card_value(card)
    value = Integer(card) rescue nil
    if value != nil
        return value
    elsif card.upcase == 'A'
        return 'A'
    else
        return 10
    end
end

def valid_card(card)
    faces = ['J', 'Q', 'K', 'A']
    value = Integer(card) rescue nil
    if (value != nil) && (value>=2 && value<=10)
        return true
    elsif value == nil
        face = card.upcase
        if faces.include?(face)
            return true
        else
            return false
        end
    end
end

def welcome
    puts "Welcome. I am your Blackjack Advisor. Please tell me your first two" +
    "cards and the dealer's upcard."
    puts
    puts "Please enter values between 2 and 10. Jack, Queens, and Kings can be"+
    " typed as J, Q, and K, respectively. You may also simply type their value"+
    " of 10. An ace must be typed as an 'A'"
    puts
end

def advice(c1, c2, up)
    h = {   'A'     => {'A' => {'A' => "hit",
                                2   => "hit",
                                3   => "hit",
                                4   => "hit",
                                5   => "hit",
                                6   => "stand",
                                7   => "stand",
                                8   => "stand",
                                9   => "stand",
                                10  => "stand"},
                        2 => {  'A' => "hit",
                                2   => "hit",
                                3   => "hit",
                                4   => "hit",
                                5   => "hit",
                                6   => "hit",
                                7   => "hit",
                                8   => "hit",
                                9   => "double down",
                                10  => "hit"},
                        3 => {  'A' => "hit",
                                2   => "hit",
                                3   => "hit",
                                4   => "hit",
                                5   => "hit",
                                6   => "hit",
                                7   => "hit",
                                8   => "double down",
                                9   => "hit",
                                10  => "hit"},
                        4 => {  'A' => "hit",
                                2   => "hit",
                                3   => "hit",
                                4   => "hit",
                                5   => "hit",
                                6   => "hit",
                                7   => "double down",
                                8   => "hit",
                                9   => "hit",
                                10  => "hit"},
                        5 => {  'A' => "hit",
                                2   => "hit",
                                3   => "hit",
                                4   => "hit",
                                5   => "hit",
                                6   => "double down",
                                7   => "hit",
                                8   => "hit",
                                9   => "hit",
                                10  => "hit"},
                        6 => {  'A' => "stand",
                                2   => "hit",
                                3   => "hit",
                                4   => "hit",
                                5   => "double down",
                                6   => "hit",
                                7   => "hit",
                                8   => "hit",
                                9   => "hit",
                                10  => "hit"},
                        7 => {  'A' => "stand",
                                2   => "hit",
                                3   => "hit",
                                4   => "double down",
                                5   => "hit",
                                6   => "hit",
                                7   => "hit",
                                8   => "hit",
                                9   => "hit",
                                10  => "stand"},
                        8 => {  'A' => "stand",
                                2   => "hit",
                                3   => "double down",
                                4   => "hit",
                                5   => "hit",
                                6   => "hit",
                                7   => "hit",
                                8   => "split",
                                9   => "stand",
                                10  => "stand"},
                        9 => {  'A' => "stand",
                                2   => "double down",
                                3   => "hit",
                                4   => "hit",
                                5   => "hit",
                                6   => "hit",
                                7   => "hit",
                                8   => "stand",
                                9   => "stand",
                                10  => "stand"},
                        10 => { 'A' => "stand",
                                2   => "hit",
                                3   => "hit",
                                4   => "hit",
                                5   => "hit",
                                6   => "hit",
                                7   => "stand",
                                8   => "stand",
                                9   => "stand",
                                10  => "stand"}},
            2       => {'A' => {'A' => "split",
                                2   => "stand",
                                3   => "stand",
                                4   => "stand",
                                5   => "stand",
                                6   => "stand",
                                7   => "stand",
                                8   => "stand",
                                9   => "stand",
                                10  => "stand"},
                        2 => {  'A' => "hit",
                                2   => "Split",
                                3   => "hit",
                                4   => "hit",
                                5   => "hit",
                                6   => "hit",
                                7   => "double down",
                                8   => "double down",
                                9   => "double down",
                                10  => "hit"},
                        3 => {  'A' => "stand",
                                2   => "hit",
                                3   => "split",
                                4   => "hit",
                                5   => "hit",
                                6   => "double down",
                                7   => "double down",
                                8   => "double down",
                                9   => "hit",
                                10  => "stand"},
                        4 => {  'A' => "stand",
                                2   => "hit",
                                3   => "hit",
                                4   => "hit",
                                5   => "double down",
                                6   => "double down",
                                7   => "double down",
                                8   => "hit",
                                9   => "stand",
                                10  => "stand"},
                        5 => {  'A' => "stand",
                                2   => "hit",
                                3   => "hit",
                                4   => "double down",
                                5   => "double down",
                                6   => "double down",
                                7   => "hit",
                                8   => "stand",
                                9   => "stand",
                                10  => "stand"},
                        6 => {  'A' => "stand",
                                2   => "hit",
                                3   => "double down",
                                4   => "double down",
                                5   => "double down",
                                6   => "split",
                                7   => "stand",
                                8   => "stand",
                                9   => "stand",
                                10  => "stand"},
                        7 => {  'A' => "stand",
                                2   => "double down",
                                3   => "double down",
                                4   => "double down",
                                5   => "hit",
                                6   => "stand",
                                7   => "split",
                                8   => "stand",
                                9   => "stand",
                                10  => "stand"},
                        8 => {  'A' => "stand",
                                2   => "double down",
                                3   => "double down",
                                4   => "hit",
                                5   => "stand",
                                6   => "stand",
                                7   => "stand",
                                8   => "split",
                                9   => "stand",
                                10  => "stand"},
                        9 => {  'A' => "stand",
                                2   => "double down",
                                3   => "hit",
                                4   => "stand",
                                5   => "stand",
                                6   => "stand",
                                7   => "stand",
                                8   => "stand",
                                9   => "split",
                                10  => "stand"},
                        10 => { 'A' => "stand",
                                2   => "hit",
                                3   => "stand",
                                4   => "stand",
                                5   => "stand",
                                6   => "stand",
                                7   => "stand",
                                8   => "stand",
                                9   => "stand",
                                10  => "stand"}},
            3       => {'A' => {'A' => "split",
                                2   => "stand",
                                3   => "stand",
                                4   => "stand",
                                5   => "stand",
                                6   => "stand",
                                7   => "stand",
                                8   => "stand",
                                9   => "stand",
                                10  => "stand"},
                        2 => {  'A' => "stand",
                                2   => "Split",
                                3   => "hit",
                                4   => "hit",
                                5   => "hit",
                                6   => "hit",
                                7   => "double down",
                                8   => "double down",
                                9   => "double down",
                                10  => "hit"},
                        3 => {  'A' => "stand",
                                2   => "hit",
                                3   => "split",
                                4   => "hit",
                                5   => "hit",
                                6   => "double down",
                                7   => "double down",
                                8   => "double down",
                                9   => "hit",
                                10  => "stand"},
                        4 => {  'A' => "stand",
                                2   => "hit",
                                3   => "hit",
                                4   => "hit",
                                5   => "double down",
                                6   => "double down",
                                7   => "double down",
                                8   => "hit",
                                9   => "stand",
                                10  => "stand"},
                        5 => {  'A' => "stand",
                                2   => "hit",
                                3   => "hit",
                                4   => "double down",
                                5   => "double down",
                                6   => "double down",
                                7   => "hit",
                                8   => "stand",
                                9   => "stand",
                                10  => "stand"},
                        6 => {  'A' => "stand",
                                2   => "hit",
                                3   => "double down",
                                4   => "double down",
                                5   => "double down",
                                6   => "split",
                                7   => "stand",
                                8   => "stand",
                                9   => "stand",
                                10  => "stand"},
                        7 => {  'A' => "stand",
                                2   => "double down",
                                3   => "double down",
                                4   => "double down",
                                5   => "hit",
                                6   => "stand",
                                7   => "split",
                                8   => "stand",
                                9   => "stand",
                                10  => "stand"},
                        8 => {  'A' => "stand",
                                2   => "double down",
                                3   => "double down",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "split",
                                9   => "",
                                10  => ""},
                        9 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "split",
                                10  => ""},
                        10 => { 'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => "stand"}},
            4       => {'A' => {'A' => "split",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        2 => {  'A' => "",
                                2   => "Split",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        3 => {  'A' => "",
                                2   => "",
                                3   => "Split",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        4 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "Hit",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        5 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "Double Down",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        6 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "split",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        7 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "split",
                                8   => "",
                                9   => "",
                                10  => ""},
                        8 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "split",
                                9   => "",
                                10  => ""},
                        9 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "split",
                                10  => ""},
                        10 => { 'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => "stand"}},
            5       => {'A' => {'A' => "split",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        2 => {  'A' => "",
                                2   => "Split",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        3 => {  'A' => "",
                                2   => "",
                                3   => "Split",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        4 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "Hitsplit",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        5 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "Double Down",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        6 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "split",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        7 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "split",
                                8   => "",
                                9   => "",
                                10  => ""},
                        8 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "split",
                                9   => "",
                                10  => ""},
                        9 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "split",
                                10  => ""},
                        10 => { 'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => "stand"}},
            6       => {'A' => {'A' => "split",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        2 => {  'A' => "",
                                2   => "Split",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        3 => {  'A' => "",
                                2   => "",
                                3   => "Split",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        4 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "Hitsplit",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        5 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "Double Down",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        6 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "split",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        7 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "split",
                                8   => "",
                                9   => "",
                                10  => ""},
                        8 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "split",
                                9   => "",
                                10  => ""},
                        9 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "split",
                                10  => ""},
                        10 => { 'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => "stand"}},
            7       => {'A' => {'A' => "split",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        2 => {  'A' => "",
                                2   => "Split",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        3 => {  'A' => "",
                                2   => "",
                                3   => "Split",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        4 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "Hit",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        5 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "Double Down",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        6 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "split",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        7 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "split",
                                8   => "",
                                9   => "",
                                10  => ""},
                        8 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "split",
                                9   => "",
                                10  => ""},
                        9 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "split",
                                10  => ""},
                        10 => { 'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => "stand"}},
            8       => {'A' => {'A' => "split",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        2 => {  'A' => "",
                                2   => "Split",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        3 => {  'A' => "",
                                2   => "",
                                3   => "Split",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        4 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "Hit",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        5 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "Double Down",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        6 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "split",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        7 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "split",
                                8   => "",
                                9   => "",
                                10  => ""},
                        8 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "split",
                                9   => "",
                                10  => ""},
                        9 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "split",
                                10  => ""},
                        10 => { 'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => "stand"}},
            9       => {'A' => {'A' => "split",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        2 => {  'A' => "",
                                2   => "Split",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        3 => {  'A' => "",
                                2   => "",
                                3   => "Split",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        4 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "Hit",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        5 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "Double Down",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        6 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "split",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        7 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "split",
                                8   => "",
                                9   => "",
                                10  => ""},
                        8 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "split",
                                9   => "",
                                10  => ""},
                        9 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "split",
                                10  => ""},
                        10 => { 'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => "stand"}},
            10      => {'A' => {'A' => "split",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        2 => {  'A' => "",
                                2   => "Split",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        3 => {  'A' => "",
                                2   => "",
                                3   => "Split",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        4 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "Hit",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        5 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "Double Down",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        6 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "split",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => ""},
                        7 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "split",
                                8   => "",
                                9   => "",
                                10  => ""},
                        8 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "split",
                                9   => "",
                                10  => ""},
                        9 => {  'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "split",
                                10  => ""},
                        10 => { 'A' => "",
                                2   => "",
                                3   => "",
                                4   => "",
                                5   => "",
                                6   => "",
                                7   => "",
                                8   => "",
                                9   => "",
                                10  => "stand"}}}
    puts
    puts "you should " + h[up][c1][c2]

end
=begin
def split(c1, c2, up)
    return nil unless c1 == c2
    if (c1 == 8) || (c1 == 'A')
        puts "Split!"
        return
end
=end
def main
    welcome
    card1, card2, upcard = ask_user
    advice(card1, card2, upcard)
    # puts "card1: " + card1.to_s
    # puts "card2: " + card2.to_s
    # puts "upcard: " + upcard.to_s
end

main
